export const t = {
  Button: 'Кнопка',
  Date: 'Дата',
  Confirm: 'Подтвердить',
  Cancel: 'Отмена',
  Open: 'Открыть',
  Close: 'Закрыть',
  Clear: 'Очистить',
  English: 'Английский',
  Russian: 'Русский',
  Uzbekistan: 'Узбекский',
  Kazakhstan: 'Казахский',
  Apply: 'Применить',
  Filters: 'Фильтры',
  Tab: 'Панель',
  Step: 'Шаг',
  Tooltip: 'Подсказка',
  Option: 'Опция',
  Search: 'Поиск',
  Copied: 'Скопировано',
  Copy: 'Копировать',
  Format: 'Формат',
  from: 'от',
  'Select from the list': 'Выберите из списка',
  'Date created': 'Дата создания',
  'copied to the exchange buffer': 'скопирован в буфер обмена',
  'Copying error': 'Ошибка при копировании',
  'No data': 'Нет данных',
  'List of documents': 'Список документов',
  'Select a file': 'Выберите файл',
  'or drag it to this window': 'или перетащите его в это окно',
  'Sort by date': 'Сортировать по дате',
  'up to': 'до',
  'Download the template': 'Загрузить шаблон',
};
