export const t = {
  Button: 'Кнопка',
  Confirm: 'Подтвердить',
  Cancel: 'Отмена',
  Open: 'Открыть',
  Close: 'Закрыть',
  'Sort by date': 'Сортировать по дате',
  Filters: 'Фильтры',
  Tab: 'Панель',
  Step: 'Шаг',
  Tooltip: 'Подсказка',
  Option: 'Опция',
  Search: 'Поиск',
  'No data': 'Нет данных',
};
