export const t = {
  Button: 'Кнопка',
  Confirm: 'Подтвердить',
  Cancel: 'Отмена',
  Open: 'Открыть',
  Close: 'Закрыть',
  Filters: 'Фильтры',
  Tab: 'Панель',
  Step: 'Шаг',
  Tooltip: 'Подсказка',
  Option: 'Опция',
  Search: 'Поиск',
  Copied: 'Скопировано',
  Copy: 'Копировать',
  Format: 'Формат',
  'No data': 'Нет данных',
  'List of documents': 'Список документов',
  'Select a file': 'Выберите файл',
  'or drag it to this window': 'или перетащите его в это окно',
  'Sort by date': 'Сортировать по дате',
  'up to': 'до',
  'Download the template': 'Загрузить шаблон',
};
